% cell array containing file names and their corresponding Google Drive IDs
file_info = { ...
    'Plaid_responses_Matlab3bis.mat', '12B42ydTCRUjR76LhG2bXlaQ3i_wHzACV'; ...
    'Grating_responses_Matlab3bis.mat', '1fnot4gTf2MTqyaEtqFgiHDAuWfdKueQE'; ...
    'Plaid_responses_Matlab3.mat', '1956OUR1Ri2C0pVvtZ7g2nOnhc3nl4YYj'; ...
    'Grating_responses_Matlab3.mat', '19xqky5NXbM8zFpOvsJubyFNjMZQkGhgv'; ...
    'Noise_responses5_Matlab2.mat', '1RtRubGvzjXervXPYR0hueVkQQr4a9yOD'; ...
    'Noise_responses8_Matlab2.mat', '13PcPgrqWYXVq8LXhU7XMjEimmPSX9XkY'; ...
    'Noise_responses1_Matlab2.mat', '1yakZkV8DNpxZ6KAiQPiwCu5RLHxaUtqI'; ...
    'Noise_responses0_Matlab2.mat', '1CbUJqSRnpY7gWP2V81N05zy0QJEibqYd'; ...
    'Noise_responses2_Matlab2.mat', '17KEYGyXWKm-fVWvnzk7wMP0Cxtx_S2sr'; ...
    'Noise_responses11_Matlab2.mat', '1ljb2n2vgfl9luvBrJ6d28JOe8lfut3Kq'; ...
    'Noise_responses17_Matlab2.mat', '1m1aCNH_QiUUAk0qSXh_P28uEjIOPYx5I'; ...
    'Noise_responses25_Matlab2.mat', '1Af6u7bvSjJpIwizEkcLGU-GCvuv5EdbR'; ...
    'Blank_responses_Matlab2.mat', '1a9RshiKp3uLy3nZ3zLAomf8IyEh9pJbd'; ...
    'Noise_responses32_Matlab2.mat', '1YnNNZpF5345wHUb2D_3PGX71XgWOeEKx'; ...
    'Plaid_responses_Matlab2.mat', '1Nk2N-LOEzA7UbnsKB7zO1cZ3jCKY5aVf'; ...
    'Noise_responses37_Matlab2.mat', '14IWJ8Ld3lK-pUvximAZbGHDNgat0M5Sc'; ...
    'Noise_responses15_Matlab2.mat', '1yvDMVQSwY_z6UHYyz9gIXHK_2hNbloRe'; ...
    'Noise_responses9_Matlab2.mat', '17PXQ1OdnTikodeWsTq8G0bGU8DsBX0YA'; ...
    'Noise_responses38_Matlab2.mat', '1N9STu224zOmAvVI1iLQLLmf-b-Lf7HN1'; ...
    'Noise_responses7_Matlab2.mat', '1g13E7GRoMP905epQf1ihQvRNw4Wxe-sS'; ...
    'Noise_responses24_Matlab2.mat', '1y_f9CzY4mimiImuTZPs3DkhpQ_EzYaS7'; ...
    'Noise_responses23_Matlab2.mat', '1_VKC0UIUUfP-Cr29fEk7fCT1ZFxkNaCi'; ...
    'Grating_responses_Matlab2.mat', '1-GdsWJhYA3U_ugu2T1TUmYOkuYLnQScS'; ...
    'Noise_responses19_Matlab2.mat', '1v9aynPc6vMKyBINPiIlPZe3Yx1S7mtUJ'; ...
    'Noise_responses33_Matlab2.mat', '1aLEe4t5WY9v7rt1kjBcm309nsnVCpJgA'; ...
    'Noise_responses39_Matlab2.mat', '1MpAP35CidWueFlXzJINiJyEDJ5lnvM1S'; ...
    'Noise_responses3_Matlab2.mat', '1CUeYM3oZ7jW17_GHxPvUkAwXEH8FeE-o'; ...
    'Noise_responses10_Matlab2.mat', '1F35VHigCbGh8X_XWgH6_EoOojPPXvGrD'; ...
    'Noise_responses20_Matlab2.mat', '131DYGam7tsRaLLr8WTvfC-0z1e_p_cwk'; ...
    'Noise_responses6_Matlab2.mat', '1vK3WLtR-8ahS1Shnwc9vodh_OPpPO75Z'; ...
    'Noise_responses4_Matlab2.mat', '1Eo6cv2lu5Y_21runukR6RtmA15KK1Joj'; ...
    'Noise_responses30_Matlab2.mat', '1TWD3W0QqiMsSZEB5swalaoVzVclcjvtu'; ...
    'Noise_responses29_Matlab2.mat', '1Pz7foKU9YjMJvtK5k50AdosW_QzFyoyN'; ...
    'Noise_responses22_Matlab2.mat', '1h5-L0TmguuXr779G8CIA-PvUBDNsxgoA'; ...
    'Noise_responses35_Matlab2.mat', '1G73ea2A_iMP2zdLPnPKTg35LQ-ZXDDtx'; ...
    'Noise_responses34_Matlab2.mat', '14WkKHqLbHNXUDs9eM-0V-b-jSK7evV6P'; ...
    'Noise_responses21_Matlab2.mat', '15n5fscSqdS4cvwKPwPwyYc_chL5ZPePL'; ...
    'Noise_responses14_Matlab2.mat', '18h7iOsiCHdMNiU4ysCVmBXsUO6UQE9Yn'; ...
    'Noise_responses26_Matlab2.mat', '1LtoM0przKfBOO3Ugx0O07Y-B6jtw904w'; ...
    'Noise_responses13_Matlab2.mat', '12ogp4wQr4z41yQmBvvkvnQ5BnXSBLoTE'; ...
    'Noise_responses27_Matlab2.mat', '1QBVDTPXlXQLHG1RTV0_RjVxhzxJ78N6Z'; ...
    'Noise_responses16_Matlab2.mat', '1ZZesVcAQVlL10NUfIPRmt6Vbu74pXxpZ'; ...
    'Noise_responses12_Matlab2.mat', '1xIdsJoajlbadWeQERGWQ-aCBZ-Q66ytt'; ...
    'Noise_responses31_Matlab2.mat', '1zM7u2hBS8fHm88QUrM4L0I823n71D9z2'; ...
    'Noise_responses18_Matlab2.mat', '1xjNAKQ6X79s7h6muuSFgbFDyQm7WeKXS'; ...
    'Noise_responses36_Matlab2.mat', '1OPfFZILRzERYg7ePog2JUYbl63-qklVy'; ...
    'Noise_responses28_Matlab2.mat', '1ML0KyBzEvE6sgkLm1gfa9duCcVSkseLO'; ...
    'Stimuli_DorsalNet_Matlab2.mat', '1c_w0kK_G_pBi9MR1V0wWcskcCkLfH7HJ' ...
};

% local folder where you want to download the files
local_folder = './downloaded_files';

% check if the folder exists, if not, create it
if ~exist(local_folder, 'dir')
    mkdir(local_folder);
end

% loop through the cell array to download each file
for i = 1:size(file_info, 1)
    
    % get current filename and fileid
    file_name = file_info{i, 1};
    file_id = file_info{i, 2};
    
    % generate the Google Drive download URL
    url = sprintf('https://drive.google.com/uc?export=download&id=%s', file_id);
    
    % specify the local path where the file will be saved
    destination = fullfile(local_folder, file_name);
    
    % download the file
    websave(destination, url);
end